export default function Terms() {
  return (
    <div
      style={{
        minHeight: "100vh",
        backgroundColor: "#f9fafb",
        padding: "2rem",
      }}
    >
      <div
        style={{
          maxWidth: "800px",
          margin: "0 auto",
          backgroundColor: "white",
          borderRadius: "12px",
          padding: "3rem",
          boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
        }}
      >
        <h1 style={{ fontSize: "2rem", fontWeight: 700, marginBottom: "1rem" }}>
          Terms of Service
        </h1>
        <p style={{ color: "#6b7280", marginBottom: "2rem" }}>
          Last updated: January 10, 2026
        </p>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            1. Acceptance of Terms
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            By accessing or using Content Engine, you agree to be bound by these Terms of
            Service. If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            2. Description of Service
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            Content Engine is an AI-powered platform that helps users create social media
            content, including slideshows and other visual content. We use artificial
            intelligence to generate images and assist with content creation.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            3. User Accounts
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            You must create an account to use certain features of our service. You are
            responsible for maintaining the confidentiality of your account credentials
            and for all activities that occur under your account. You must provide accurate
            and complete information when creating your account.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            4. User Content
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            You retain ownership of any content you create using our platform. By using our
            service, you grant us a limited license to store and process your content as
            necessary to provide the service. You are responsible for ensuring your content
            does not violate any laws or third-party rights.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            5. Acceptable Use
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            You agree not to use our service to create content that is illegal, harmful,
            threatening, abusive, harassing, defamatory, or otherwise objectionable. You
            may not use our service to infringe on intellectual property rights or to
            distribute malware or spam.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            6. AI-Generated Content
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            Content generated by our AI tools is provided "as is." While we strive for
            high-quality output, we do not guarantee that AI-generated content will be
            accurate, appropriate, or suitable for any particular purpose. You are
            responsible for reviewing and editing all content before use.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            7. Intellectual Property
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            The Content Engine platform, including its design, features, and code, is owned
            by us and protected by intellectual property laws. You may not copy, modify, or
            distribute our platform without permission.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            8. Limitation of Liability
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            To the maximum extent permitted by law, Content Engine shall not be liable for
            any indirect, incidental, special, consequential, or punitive damages arising
            from your use of our service. Our total liability shall not exceed the amount
            you paid us in the past twelve months.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            9. Termination
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            We may terminate or suspend your account at any time for violations of these
            terms or for any other reason at our discretion. You may also terminate your
            account at any time by contacting us.
          </p>
        </section>

        <section style={{ marginBottom: "2rem" }}>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            10. Changes to Terms
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            We may update these terms from time to time. We will notify you of significant
            changes by posting a notice on our platform or by email. Continued use of our
            service after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: "1.25rem", fontWeight: 600, marginBottom: "0.75rem" }}>
            11. Contact Us
          </h2>
          <p style={{ color: "#374151", lineHeight: 1.7 }}>
            If you have any questions about these Terms of Service, please contact us at
            legal@content-engine.dev.
          </p>
        </section>

        <div style={{ marginTop: "3rem", paddingTop: "1.5rem", borderTop: "1px solid #e5e7eb" }}>
          <a
            href="/"
            style={{
              color: "#3b82f6",
              textDecoration: "none",
              fontWeight: 500,
            }}
          >
            &larr; Back to Home
          </a>
        </div>
      </div>
    </div>
  );
}
